### ISSUE TITLE
Issue with running test script

### ISSUE THREAD

**Issue by m-gemmell** [homopolymer/RAMBL#1]
Dear Developers

I have been trying to install and run rambl but I have not been able to get it working. Would you be able to help?

Below is the test command and the screen output when running it. I am using conda to get all the specific dependencies for rambl. If you are willing to help and need any more information please do not hesitate to ask.

(rambl) matt@gauss04:~/tests/rambl/RAMBL_Test$ python ~/programs_chos_8/rambl/RAMBL/bin/rambl.py -c 20 -v data_info.txt 2>&1 | tee log.txt
[2017-04-24 15:56:55,919] INFO : profile sequencing depths
[2017-04-24 15:56:56,128] INFO : 1 bam files in total, and split to 1 parts
[2017-04-24 15:56:56,131] INFO : work in temporary dir /tmp/tmpJLKmiR
[2017-04-24 15:56:56,149] INFO : calculate depth on bamlist#0 to /tmp/tmpJLKmiR/depth_on_local_bamlist_0.cov
[2017-04-24 15:56:57,447] INFO : save depth of bamlist#0 to /tmp/tmpJLKmiR/depth_on_local_bamlist_0.bed
[2017-04-24 15:57:03,158] INFO : merge the results
[2017-04-24 15:57:03,159] INFO : join 1 depth-files in total size 25.96105 Mb
[2017-04-24 15:57:03,214] INFO : split 1502469 nucleotide positions into 1 parts of each with 1502469 positions
[2017-04-24 15:57:03,286] INFO : summarize nucleotide-based depth on cpu0
[2017-04-24 15:57:05,642] INFO : run bedtools-merge on cpu0
[2017-04-24 15:57:06,992] INFO : merge 1 parts, then sort
[2017-04-24 15:57:07,094] INFO : rm /tmp/tmpJLKmiR
[2017-04-24 15:57:07,095] INFO : complete
[2017-04-24 15:57:07,096] INFO : elapsed time is 0.18283 minutes
[2017-04-24 15:57:07,120] INFO : compute gene abundance
[2017-04-24 15:57:07,275] INFO : load gene info from /pub37/matt/tests/rambl/RAMBL_Test/99_otus.fasta.fai
[2017-04-24 15:57:07,569] INFO : process records in /pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/gene_depth.txt
[2017-04-24 15:57:07,697] INFO : done
[2017-04-24 15:57:07,708] INFO : elapsed time is 0.00724 minutes
[2017-04-24 15:57:07,719] INFO : find seed genes
[2017-04-24 15:57:09,233] INFO : map gene reads to seed genes
[2017-04-24 15:57:09,360] INFO : start from building the mapping index
[2017-04-24 15:57:09,361] INFO : build the bowtie2 index file
[2017-04-24 15:57:11,603] INFO : elapsed time on building the bowtie2 index file is 0.03737 minutes
[2017-04-24 15:57:11,604] INFO : dump reads from 1 bam files using 1 cores
[2017-04-24 15:57:11,618] INFO : subprocess: extract reads from 1 bam files
[2017-04-24 15:57:15,326] INFO : elapsed time on dumping reads from 1 bam files is 0.062029 minutes
[2017-04-24 15:57:15,327] INFO : use bowtie2 to map reads onto 0 seed otus with 20 cores
sh: 1: Syntax error: Bad fd number
sh: 1: Syntax error: Bad fd number
[2017-04-24 15:57:15,331] INFO : elapsed time on mapping reads onto seed otus is 6e-05 minutes
[main_samview] fail to open "to_seed_otus.all.sam" for reading.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
mv: cannot stat ‘to_seed_otus.all.bam.sort.bam’: No such file or directory
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_index_core] Invalid BAM header.[bam_index_build2] fail to index the BAM file.
[2017-04-24 15:57:15,371] INFO : total elapsed time is 0.100178448359 minutes
[2017-04-24 15:57:15,381] ERROR : ERROR, UNEXPECTED EXCEPTION
Traceback (most recent call last):
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 298, in <module>
    rambl_pipe(GeneData,SeqData)
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 232, in rambl_pipe
    strain_call(TmpDir)
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 172, in strain_call
    with open(os.path.join(TmpDir,'0_otu_dir/seed_otus.fasta.fai')) as f:
IOError: [Errno 2] No such file or directory: '/pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/0_otu_dir/seed_otus.fasta.fai'
[2017-04-24 15:57:15,382] ERROR : [Errno 2] No such file or directory: '/pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/0_otu_dir/seed_otus.fasta.fai'
Traceback (most recent call last):
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 298, in <module>
    rambl_pipe(GeneData,SeqData)
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 232, in rambl_pipe
    strain_call(TmpDir)
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 172, in strain_call
    with open(os.path.join(TmpDir,'0_otu_dir/seed_otus.fasta.fai')) as f:
IOError: [Errno 2] No such file or directory: '/pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/0_otu_dir/seed_otus.fasta.fai'
Traceback (most recent call last):
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 298, in <module>
    rambl_pipe(GeneData,SeqData)
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 232, in rambl_pipe
    strain_call(TmpDir)
  File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 172, in strain_call
    with open(os.path.join(TmpDir,'0_otu_dir/seed_otus.fasta.fai')) as f:
IOError: [Errno 2] No such file or directory: '/pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/0_otu_dir/seed_otus.fasta.fai'

Thanks for reading
Matthew Gemmell

**Comment by homopolymer** [comment]
Dear Matthew,
Thanks for trying our tool. I scan through the log info that you provided. The problem is that RAMBL didn't find the seed OTUs, and is probably caused by the external tools that are too new. I give a list of tools and their versions that we use in our server as follows.

samtools    0.1.19    (Samtools of new version has many different command line options compared with the old version. It is a major reason causing the failure of RAMBL, according to the feedbacks of our collaborators.)
bedtools     2.24.0 
bowtie2      2.3.0
sickle          1.33
seqtk           1.0
ete2            2.3.1


 

    On Monday, April 24, 2017 11:02 PM, Matthew Gemmell <notifications@github.com> wrote:
 

 Dear DevelopersI have been trying to install and run rambl but I have not been able to get it working. Would you be able to help?Below is the test command and the screen output when running it. I am using conda to get all the specific dependencies for rambl. If you are willing to help and need any more information please do not hesitate to ask.(rambl) matt@gauss04:~/tests/rambl/RAMBL_Test$ python ~/programs_chos_8/rambl/RAMBL/bin/rambl.py -c 20 -v data_info.txt 2>&1 | tee log.txt
[2017-04-24 15:56:55,919] INFO : profile sequencing depths
[2017-04-24 15:56:56,128] INFO : 1 bam files in total, and split to 1 parts
[2017-04-24 15:56:56,131] INFO : work in temporary dir /tmp/tmpJLKmiR
[2017-04-24 15:56:56,149] INFO : calculate depth on bamlist#0 to /tmp/tmpJLKmiR/depth_on_local_bamlist_0.cov
[2017-04-24 15:56:57,447] INFO : save depth of bamlist#0 to /tmp/tmpJLKmiR/depth_on_local_bamlist_0.bed
[2017-04-24 15:57:03,158] INFO : merge the results
[2017-04-24 15:57:03,159] INFO : join 1 depth-files in total size 25.96105 Mb
[2017-04-24 15:57:03,214] INFO : split 1502469 nucleotide positions into 1 parts of each with 1502469 positions
[2017-04-24 15:57:03,286] INFO : summarize nucleotide-based depth on cpu0
[2017-04-24 15:57:05,642] INFO : run bedtools-merge on cpu0
[2017-04-24 15:57:06,992] INFO : merge 1 parts, then sort
[2017-04-24 15:57:07,094] INFO : rm /tmp/tmpJLKmiR
[2017-04-24 15:57:07,095] INFO : complete
[2017-04-24 15:57:07,096] INFO : elapsed time is 0.18283 minutes
[2017-04-24 15:57:07,120] INFO : compute gene abundance
[2017-04-24 15:57:07,275] INFO : load gene info from /pub37/matt/tests/rambl/RAMBL_Test/99_otus.fasta.fai
[2017-04-24 15:57:07,569] INFO : process records in /pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/gene_depth.txt
[2017-04-24 15:57:07,697] INFO : done
[2017-04-24 15:57:07,708] INFO : elapsed time is 0.00724 minutes
[2017-04-24 15:57:07,719] INFO : find seed genes
[2017-04-24 15:57:09,233] INFO : map gene reads to seed genes
[2017-04-24 15:57:09,360] INFO : start from building the mapping index
[2017-04-24 15:57:09,361] INFO : build the bowtie2 index file
[2017-04-24 15:57:11,603] INFO : elapsed time on building the bowtie2 index file is 0.03737 minutes
[2017-04-24 15:57:11,604] INFO : dump reads from 1 bam files using 1 cores
[2017-04-24 15:57:11,618] INFO : subprocess: extract reads from 1 bam files
[2017-04-24 15:57:15,326] INFO : elapsed time on dumping reads from 1 bam files is 0.062029 minutes
[2017-04-24 15:57:15,327] INFO : use bowtie2 to map reads onto 0 seed otus with 20 cores
sh: 1: Syntax error: Bad fd number
sh: 1: Syntax error: Bad fd number
[2017-04-24 15:57:15,331] INFO : elapsed time on mapping reads onto seed otus is 6e-05 minutes
[main_samview] fail to open "to_seed_otus.all.sam" for reading.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
mv: cannot stat ‘to_seed_otus.all.bam.sort.bam’: No such file or directory
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_index_core] Invalid BAM header.[bam_index_build2] fail to index the BAM file.
[2017-04-24 15:57:15,371] INFO : total elapsed time is 0.100178448359 minutes
[2017-04-24 15:57:15,381] ERROR : ERROR, UNEXPECTED EXCEPTION
Traceback (most recent call last):
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 298, in 
rambl_pipe(GeneData,SeqData)
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 232, in rambl_pipe
strain_call(TmpDir)
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 172, in strain_call
with open(os.path.join(TmpDir,'0_otu_dir/seed_otus.fasta.fai')) as f:
IOError: [Errno 2] No such file or directory: '/pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/0_otu_dir/seed_otus.fasta.fai'
[2017-04-24 15:57:15,382] ERROR : [Errno 2] No such file or directory: '/pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/0_otu_dir/seed_otus.fasta.fai'
Traceback (most recent call last):
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 298, in 
rambl_pipe(GeneData,SeqData)
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 232, in rambl_pipe
strain_call(TmpDir)
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 172, in strain_call
with open(os.path.join(TmpDir,'0_otu_dir/seed_otus.fasta.fai')) as f:
IOError: [Errno 2] No such file or directory: '/pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/0_otu_dir/seed_otus.fasta.fai'
Traceback (most recent call last):
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 298, in 
rambl_pipe(GeneData,SeqData)
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 232, in rambl_pipe
strain_call(TmpDir)
File "/pub37/matt/programs_chos_8/rambl/RAMBL/bin/rambl.py", line 172, in strain_call
with open(os.path.join(TmpDir,'0_otu_dir/seed_otus.fasta.fai')) as f:
IOError: [Errno 2] No such file or directory: '/pub37/matt/tests/rambl/RAMBL_Test/RAMBL_work_dir_TjH6U/0_otu_dir/seed_otus.fasta.fai'Thanks for reading
Matthew Gemmell—

**Comment by m-gemmell** [comment]
Hello

Thanks for the prompt reply

I have checked my program versions and they all appear to be the correct version. They are below

(rambl) matt@gauss04:~/tests/rambl/RAMBL_Test$ samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.19-44428cd

Usage:   samtools <command> [options]

Command: view        SAM<->BAM conversion
         sort        sort alignment file
         mpileup     multi-way pileup
         depth       compute the depth
         faidx       index/extract FASTA
         tview       text alignment viewer
         index       index alignment
         idxstats    BAM index stats (r595 or later)
         fixmate     fix mate information
         flagstat    simple stats
         calmd       recalculate MD/NM tags and '=' bases
         merge       merge sorted alignments
         rmdup       remove PCR duplicates
         reheader    replace BAM header
         cat         concatenate BAMs
         bedcov      read depth per BED region
         targetcut   cut fosmid regions (for fosmid pool only)
         phase       phase heterozygotes
         bamshuf     shuffle and group alignments by name

(rambl) matt@gauss04:~/tests/rambl/RAMBL_Test$ bedtools --version
bedtools v2.24.0
(rambl) matt@gauss04:~/tests/rambl/RAMBL_Test$ bowtie2 --version
/pub37/matt/programs/anaconda2/envs/rambl/bin/bowtie2-align-s version 2.3.0
64-bit
Built on testing-gce-d041cceb-46b2-45bd-9fae-acee9d45f743
Sun Jan 22 15:27:15 UTC 2017
Compiler: gcc version 4.8.5 (GCC) 
Options: -O3 -m64 -msse2 -funroll-loops -g3 -I/pub37/matt/programs/anaconda2/envs/rambl/include -L/pub37/matt/programs/anaconda2/envs/rambl/lib -DPOPCNT_CAPABILITY -DWITH_TBB -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}
(rambl) matt@gauss04:~/tests/rambl/RAMBL_Test$ sickle --version
sickle version 1.33
Copyright (c) 2011 The Regents of University of California, Davis Campus.
sickle is free software and comes with ABSOLUTELY NO WARRANTY.
Distributed under the MIT License.

Written by Nikhil Joshi, UC Davis Bioinformatics Core

(rambl) matt@gauss04:~/tests/rambl/RAMBL_Test$ seqtk

Usage:   seqtk <command> <arguments>
Version: 1.0-r31

Command: seq       common transformation of FASTA/Q
         comp      get the nucleotide composition of FASTA/Q
         sample    subsample sequences
         subseq    extract subsequences from FASTA/Q
         trimfq    trim FASTQ using the Phred algorithm

         hety      regional heterozygosity
         mutfa     point mutate FASTA at specified positions
         mergefa   merge two FASTA/Q files
         randbase  choose a random base from hets
         cutN      cut sequence at long N
         listhet   extract the position of each het

(rambl) matt@gauss04:~/tests/rambl/RAMBL_Test$ pip freeze
backports.shutil-get-terminal-size==1.0.0
biopython==1.68
bz2file==0.98
CacheControl==0.11.7
contextlib2==0.5.4
cycler==0.10.0
decorator==4.0.11
enum34==1.1.6
ete2==2.3.10
functools32==3.2.3.post2
future==0.16.0
ipython==5.3.0
ipython-genutils==0.2.0
lockfile==0.12.2
lxml==3.7.3
matplotlib==2.0.0
natsort==5.0.2
nose==1.3.7
numpy==1.12.1
pandas==0.19.2
pathlib2==2.2.1
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pycairo==1.10.0
Pygments==2.2.0
pyparsing==2.1.4
python-dateutil==2.6.0
pytz==2017.2
requests==2.13.0
scandir==1.5
scikit-bio==0.4.2
scipy==0.19.0
simplegeneric==0.8.1
six==1.10.0
subprocess32==3.2.7
traitlets==4.3.2
wcwidth==0.1.7

With these I am still getting the same issue. Is there anything else you would suggest I carry out to troubleshoot the issue.

Thanks for reading
Matthew Gemmell

**Comment by homopolymer** [comment]
I create virtual envs in three different machines, (A) a CentOS of 256GB memory, (B) a Ubuntu of 16GB memory, and (C) a Ubuntu on VMware of 4GB memory. Both (A) and (B) work well. (C) has the errors like you provided. It is because that the VMware kills a RAMBL's inner process as it has no enough memory for the process to load 16S reference alignments.   
The attached is the snapshot of the message on (C). Another error "bad fd number" colored in green is caused by that Ubuntu uses Dash as the default shell environment. Can run, ll `which sh`, to check which shell is used by the operating system. RAMBL uses Bash.

**Comment by ArnauVich** [comment]
Dear Developers, 

 Following the previous discussion I would like to ask if there is any plan to adapt the code to a newer version of SAMtools. I'm struggling with a similar problem as previously described:

**[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files**
**mv: cannot stat `to_seed_otus.all.bam.sort.bam': No such file or directory
**[E::hts_idx_push] chromosome blocks not continuous**
**samtools index: "to_seed_otus.all.bam" is corrupted or unsorted****
 
Thanks and kind regards.
